### ISSUE TITLE
use pinned reactions in emoji picker

### ISSUE THREAD

**Issue by tastytea** [poppingmoon/aria#333]
### Summary

please get the preselected emoji reactions (from settings->Emoji picker in the web UI) and display them in the emoji picker

### Purpose

it's faster to find the right reaction than with the recently used list and i like to have some reactions in it that i use seldomly but are hard to search for (because of too many similar named reactions)

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
As a third party client, Aria cannot access your emoji pickers for Misskey Web since they are stored in the system domain of the registry.
However, you can open the registry on Misskey Web and manually copy and paste them to Aria. See "Settings" -> "Settings for _your account_" -> "Emoji picker" -> "Paste" in Aria for details.

**Comment by tastytea** [comment]
oooh, i didn't see that, thank you! 💖

(in case others stumble upon this: the registry in Sharkey gave me a TypeError, but searching in the Firefox developer tools, in the Storage tab, for “pinnedEmojis” brought me to the emoji array)
