### ISSUE TITLE
Remove related tabs when users sign-out of an account

### ISSUE THREAD

**Issue by foss-** [poppingmoon/aria#337]
### Summary

When signing out of an account, that account is gone from aria. However for me, the home tab remains visible at the top. Opening Settings > Tabs shows all tabs, but can't find an option to remove a tab. Tried long-pressing or swiping, but no delete option shows up.

### Purpose

Offer a simple way to remove a tab. Ideally automatically remove tabs for a related account when users sign out of that account.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
You can remove a tab on the settings page of the tab. Tap the menu button at the top right and tap "Delete".

Miria deletes tabs on signing out, but I have removed the feature for Aria because in some cases like the access token is revoked, I want to sign out and then sign in again without dropping tabs.
However, I agree that it is hard to delete multiple tabs, and for most cases, users sign out from an account because they will not use it for the app, so I will add the feature as an option by showing a dialog after signing out.

**Comment by foss-** [comment]
oh wow. I totally overlooked the `...` top right button hiding the delete option.

Adding the delete option at the end of the settings - tabs options may increase discoverability.
