### ISSUE TITLE
Reposting doesn't higlight the repost/renote icon on the original post

### ISSUE THREAD

**Issue by whitelotuz** [poppingmoon/aria#391]
### 💡 Summary

When you repost/renote a post from someone else, the icon remains the same, making it difficult to know if you have previously reposted it

### 🥰 Expected Behavior

On misskey/sharkey web, when you repost/renote something its icon is highlighted and the number count increments by 1

![image](https://github.com/user-attachments/assets/d9da6b0c-ba08-4bad-9bcd-b8f18713cbda)

### 🤬 Actual Behavior

Currently the number right next to the icon does increment, but the icon remains without highlight

### 📝 Steps to Reproduce

Repost a post from someone else that you haven't reposted yet

### 💻 Environment

```markdown
* Model and OS of the device(s): Android Pixel
* Aria: 0.14.4
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
This seems to be a Sharkey-specific feature implemented in https://activitypub.software/TransFem-org/Sharkey/-/commit/363df5b2560f7bf1ddb08f3a129e96fdf93d1442.

We can't implement this in the same manner as them because Misskey does not offer an API to get renotes from a specific user, unlike Sharkey does. They have added the option in https://activitypub.software/TransFem-org/Sharkey/-/commit/23e0daed4e9f6f0f5cd17d3ebc828d3f89f30a0c.

However, changing the color as a user taps the button is not so hard to implement. It is profitable for showing interaction and enables quick unrenote. So I will implement this using local states, not with API calls, which means renote buttons will not always be colored if you have renoted the note from a different widget.

**Comment by whitelotuz** [comment]
I see makes sense. I like the local workaround even with its limitations since its not a direct API call. Still just a nice to have!

**Comment by whitelotuz** [comment]
I remembered today this setting existed, I wonder if you could just reuse whatever validation it has for renotes to highlight the renote icon? 

![Screenshot_20240917-221649](https://github.com/user-attachments/assets/2509ce80-57c8-413c-85db-dd6ed63dba33)

**Comment by poppingmoon** [comment]
What this option actually collapses are

- All renotes of notes you have reacted
- All renotes of your notes
- Your renotes of notes

and doesn't collapse other users' renotes of notes you have renoted.

https://github.com/misskey-dev/misskey/blob/3bf63dd9c5b47f42bcbe70a96c0a5186f087330a/packages/frontend/src/components/MkNote.vue#L270-L275

https://github.com/poppingmoon/aria/blob/a023375083b6d87238c5a0998bf82b27abb7a153/lib/view/widget/note_widget.dart#L208-L215

So we can't use this to determine if notes have already been renoted, but it will be good to highlight the buttons in the current user's renotes, in addition to the notes in interaction.
